'use client';
import { Poppins } from "next/font/google";
import "./globals.css";
import { CartContextProvider } from "@/components/CartContext";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: '100'
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <CartContextProvider>
          {children}
        </CartContextProvider>
      </body>
    </html>
  );
}
