'use client';
import { Poppins } from "next/font/google";
import "./globals.css";
import { CartContextProvider } from "@/components/CartContext";
import Script from "next/script"; 

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: '100'
});

// Optional: keep metadata if you want SEO improvements
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://js.paystack.co/v1/inline.js"
          strategy="afterInteractive"
        />
      </head>
      <body className={`${poppins.variable} antialiased`}>
        <CartContextProvider>
          {children}
        </CartContextProvider>
      </body>
    </html>
  );
}
